language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5

compiler:
    - gcc

before_script:
    - mkdir build
    - cd build
    - eval “CC=gcc-5 && CXX=g++-5”
    - cmake -DSPARQL=1 -DJAVA=1 ..

script:
    - make

dist: trusty
sudo: false
